[env]
build_flags = -I../../firmware/config

[env:lolin_s3]
platform        = espressif32
board           = lolin_s3
framework       = arduino
monitor_speed   = 115200
upload_protocol = esptool
build_flags     = ${env.build_flags} -DCORE_DEBUG_LEVEL=3

[env:native]
platform        = native
build_flags     = ${env.build_flags} -DUNIT_TEST -DNATIVE_TEST -I test
test_framework  = unity
; Point to Code::Blocks MinGW installation
build_type = release
extra_scripts = pre:set_compiler.py
; For native environment: Use `pio test -e native` (not `pio run -e native`)
; This excludes src files since they require Arduino framework
build_src_filter = -<*> +<../test/mock_gpio.cpp> +<../test/include_lib.cpp>
