[env]
build_flags = -I../../firmware/config

[env:lolin_s3]
platform        = espressif32
board           = lolin_s3
framework       = arduino
monitor_speed   = 115200
upload_protocol = esptool
build_flags     = ${env.build_flags} -DCORE_DEBUG_LEVEL=3
                  -DCONFIG_NVS_LOG_CAPACITY=100

[env:native]
platform        = native
build_flags     = ${env.build_flags} -DUNIT_TEST -I test
test_framework  = unity
build_type      = release
extra_scripts   = pre:set_compiler.py
build_src_filter = -<*> +<../test/mock_nvs.cpp> +<../test/include_lib.cpp>
