[env:lolin_s3]
platform        = espressif32
board           = lolin_s3
framework       = arduino
monitor_speed   = 115200
upload_protocol = esptool
build_flags     = -I../../firmware/config -DCORE_DEBUG_LEVEL=3
lib_extra_dirs  = ../gpio
