[env:lolin_s3]
platform               = espressif32
board                  = lolin_s3
framework              = arduino
monitor_speed          = 115200
upload_protocol        = esptool
upload_port            = COM3
monitor_port           = COM3
build_flags            = -DCORE_DEBUG_LEVEL=3
board_build.filesystem = littlefs
board_build.partitions = partitions.csv

[env:native]
platform        = native
build_flags     = -DUNIT_TEST -I test
test_framework  = unity
build_type      = release
extra_scripts   = pre:set_compiler.py
build_src_filter = -<*> +<../test/mock_lfs.cpp> +<../test/include_lib.cpp>
